# Generated by Django 4.1.12 on 2023-10-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="status",
            field=models.CharField(default="ongoing", max_length=20),
        ),
    ]
