# Generated by Django 4.1.12 on 2023-10-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_election_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(default="00000", max_length=5)),
            ],
        ),
    ]
