# Generated by Django 4.1.12 on 2023-10-29 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0003_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="profile_pic",
            field=models.ImageField(default="default.png", upload_to="image/"),
        ),
        migrations.CreateModel(
            name="VoterID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voterid",
                    models.CharField(default="No Voter ID found", max_length=255),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
