# Generated by Django 4.1.12 on 2023-10-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_candidate_profile_pic_voterid"),
    ]

    operations = [
        migrations.AddField(
            model_name="voterid",
            name="address",
            field=models.CharField(
                default="XYZ, street no 52, UP, 2011150", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="voterid",
            name="age",
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name="voterid",
            name="mobile_number",
            field=models.PositiveBigIntegerField(default=9000448844),
        ),
        migrations.AddField(
            model_name="voterid",
            name="name",
            field=models.CharField(default="John Doe", max_length=255),
        ),
        migrations.AddField(
            model_name="voterid",
            name="parents_name",
            field=models.CharField(default="Papa John Doe", max_length=500),
        ),
    ]
