# Generated by Django 4.1.12 on 2023-10-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_voterid_address_voterid_age_voterid_mobile_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voterid",
            name="profile_picture",
            field=models.ImageField(default="default.png", upload_to="profile_pic"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="profile_pic",
            field=models.ImageField(default="default.png", upload_to="image"),
        ),
    ]
