# Generated by Django 4.1.12 on 2023-10-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_voterid_profile_picture_alter_candidate_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="voterid",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("blocked", "blocked")],
                default="active",
                max_length=20,
            ),
        ),
    ]
