# Generated by Django 4.1.12 on 2023-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_voterid_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "ongoing"), ("done", "done")],
                default="ongoing",
                max_length=20,
            ),
        ),
    ]
