# Generated by Django 4.1.12 on 2023-10-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_alter_election_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voterid",
            old_name="profile_picture",
            new_name="profile_pic",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="profile_pic",
            field=models.ImageField(default="image/default.png", upload_to="image"),
        ),
    ]
